title: Notes About Things 
email: email@michaelhaslauer.de
description: Notes about mostly developing software and everything i want to remember. 

domain: haslauer.github.io 
baseurl: "/notes"
url: "https://haslauer.github.io"

list_title: "Notesa"

theme: minima

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
