title: Some notes ...
email: email@michaelhaslauer.de
description: Some notes about stuff. 

domain: haslauer.github.io 
baseurl: "/notes/"
url: "https://haslauer.github.io"

theme: jekyll-theme-cayman

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
